BIN = main
CC = clang
FLAGS = -Wall -pedantic -std=c++11
INC = -I common/include -I/sw/include -I/usr/local/include
LIB_PATH = common/osx_64/
LOC_LIB = 
DYN_LIB = -lGLEW -lglfw
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = main.cpp

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${DYN_LIB}


