BIN = bin/main.exe
CC = g++
FLAGS = -Wall -pedantic -std=c++17
INC = -I common/include
LOC_LIB = common/win32/libglew32.dll.a common/win32/glfw3dll.a
SYS_LIB = -lOpenGL32 -L ./ -lglew32 -lglfw3 -lm
SRC = $(wildcard src/*.cpp)

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}

